trigger:
- main
- containerize
 
pr:
  - none
 
pool:
  vmImage: ubuntu-20.04
 
name: '$(Build.BuildId)-$(Build.SourceBranchName)'
 
resources:
  repositories:
  - repository: ado-build-templates
    type: github
    endpoint: MFAbdulMuksith
    name: MFAbdulMuksith/ado-build-templates
    ref: master
 
variables:
  - group: dev
 
stages:
  - stage: Build
    displayName: Build
    jobs:
      - template: build/build-docker-and-push-to-ecr.yaml@ado-build-templates
