# Starter pipeline
# https://www.devguides.dev/how-to-build-and-deploy-docker-images-from-azure-devops-to-aws-ecr/
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- master
pool:
  name: Mumbai.EC2.t2

name: '$(Build.BuildId)-$(Build.SourceBranchName)'
 
resources:
  repositories:
  - repository: angular-social-network
    type: github
    endpoint: angular-social-network
    name: my-anguler-app
    ref: main
 
variables:
  - group: dev
