# This pipeline builds and pushes a Docker image to AWS ECR
# create a service connection to AWS ECR and name it 'aws-ecr-connection'
# set the following environment variables:
# - AWS_ECR_REGISTRY: the name of  AWS ECR registry
# - AWS_ECR_REPOSITORY: the name of  AWS ECR repository
# - DOCKERFILE_PATH: the path to  Dockerfile
# - IMAGE_TAG: the tag for  Docker image

trigger:
- master

pool:
  name: Mumbai.EC2.t2

steps:
- task: Docker@2
  displayName: Login to AWS ECR
  inputs:
    containerRegistry: 'aws-ecr-connection'
    command: 'login'

- task: Docker@2
  displayName: Build and push Docker image
  inputs:
    containerRegistry: 'aws-ecr-connection'
    repository: '$(AWS_ECR_REGISTRY)/$(AWS_ECR_REPOSITORY)'
    command: 'buildAndPush'
    Dockerfile: '$(DOCKERFILE_PATH)'
    tags: '$(IMAGE_TAG)'