# This pipeline builds and pushes a Docker image to AWS ECR
# create a service connection to AWS ECR and name it 'aws-ecr-connection'
# set the following environment variables:

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'  

jobs:
- job: BuildAndPush
  displayName: 'Build and Push to ECR'
  steps:
  - task: ECRPushImage@1
    displayName: 'Push Docker Image to Amazon ECR'
    inputs:
      awsCredentials: 'aws-ecr-connection'
      regionName: 'ap-south-1'
      imageSource: 'containerRegistry'  
      sourceImageName: 'my-angular-app'  
      repositoryName: 'my-angular-app'
      forceDockerNamingConventions: true