# This pipeline builds and pushes a Docker image to AWS ECR
# create a service connection to AWS ECR and name it 'aws-ecr-connection'
# set the following environment variables:

trigger:
- master

pool:
  name: 'Azure Pipelines'

variables:
  awsRegion: 'ap-south-1'
  ecrRepository: 'my-angular-app'

jobs:
- job: BuildAndPush
  displayName: 'Build and Push to ECR'
  steps:
  - task: ECRPushImage@1
    displayName: 'Push Docker Image to Amazon ECR'
    inputs:
      awsCredentials: 'aws-ecr-connection'
      regionName: '$(awsRegion)'
      imageSource: 'containerRegistry'
      repositoryName: '$(ecrRepository)'
      forceDockerNamingConventions: true