trigger:
- main

pool:
  name: 

jobs:
- job: Build
  displayName: 'Build Angular App'
  pool:
    name: 'YourSelfHostedAgentPoolName'
  steps:
  - script: |
      pwd 
      ls -al
    displayName: 'Build Angular Application'