# build/build-docker-and-push-to-ecr.yaml
parameters:
- name: dockerfile
  type: string
  default: Dockerfile
- name: imageRepository
  type: string
  default: my-angular-app
- name: containerRegistry
  type: string
  default: myecr
- name: repository
  type: string
  default: my-angular-app
- name: tag
  type: string
  default: $(Build.BuildId)

steps:
- task: Docker@2
  displayName: Login to ECR
  inputs:
    command: login
    containerRegistry: ${{ parameters.containerRegistry }}

- task: Docker@2
  displayName: Build and push image
  inputs:
    command: buildAndPush
    repository: ${{ parameters.repository }}
    dockerfile: ${{ parameters.dockerfile }}
    containerRegistry: ${{ parameters.containerRegistry }}
    tags: |
      ${{ parameters.tag }}
