# Starter pipeline
# https://www.devguides.dev/how-to-build-and-deploy-docker-images-from-azure-devops-to-aws-ecr/
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
  branches:
    include:
      - master
pool:
  name: Mumbai.EC2.t2
variables:
  - group: dev
  - name: DOCKER_REPOSITORY
    value: >-
      $(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com/$(DOCKER_REPOSITORY_NAME)
  - task: ECRPushImage@1
    inputs:
      awsCredentials: my-AWS-connection
      regionName: ap-south-1
      imageSource: imagename
      sourceImageName: '**'
      repositoryName: '**'

