# This pipeline builds and pushes a Docker image to AWS ECR
# create a service connection to AWS ECR and name it 'aws-ecr-connection'
# set the following environment variables:

trigger:
  branches:
    include:
      - master
pr: none
stages:

  - stage: AdditionalStage
    jobs:
    - job: CustomJob
      steps:
      - script: echo "Custom job steps"

  - stage: Docker
    displayName: Build & Push Docker image to AWS ECR
    jobs:
      - job: Build_and_Push
        displayName: Build & Push Docker image
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            displayName: Build an image
            inputs:
              command: build
              dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
              buildContext: '$(Build.SourcesDirectory)'
              repository: $(DOCKER_REPOSITORY_NAME)

          - task: ECRPushImage@1
            inputs:
              awsCredentials: 'AWS_ECR'
              regionName: $(AWS_REGION)
              imageSource: 'imagename'
              sourceImageName: $(DOCKER_REPOSITORY_NAME)
              sourceImageTag: $(Build.BuildId)
              pushTag: latest
              repositoryName: $(DOCKER_REPOSITORY_NAME)