# https://github.com/MFAbdulMuksith/ado-build-template.git branch main

trigger:
- main

pool:
  vmImage: ubuntu-20.04

name: '$(Build.BuildId)-$(Build.SourceBranchName)'

resources:
  repositories:
  - repository: ado-build-templates
    type: github
    endpoint: MFAbdulMuksith
    name: MFAbdulMuksith/ado-build-template 
    ref: main

variables:
- group: my-angular-app

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: BuildDocker
    displayName: Build Docker Image and Push to ECR
    steps:
    - template: build/build-docker-and-push-to-ecr.yaml@ado-build-templates # change the path to include the build folder
      parameters:
        dockerfile: Dockerfile
        imageRepository: my-angular-app
        containerRegistry: myecr
        repository: my-angular-app
        tag: $(Build.BuildId)
