# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Mumbai.EC2.t2

stages:
- stage: Build
  displayName: 'Build stage'
  jobs:
    - job: BuildJob
      displayName: 'Build Job'
      pool:
        name: Mumbai.EC2.t2
      steps:
        - task: CmdLine@2
          displayName: 'builds'
          inputs:
            script: |
              pwd
              ls -al
              sudo docker build -t angular-img .
              sudo docker stop angular-cont
              sudo docker images
              sudo docker rm angular-cont
              sudo docker run -d -p 80:80 --name angular-cont angular-img
              sudo docker ps
              echo "Visit http://52.66.246.156:80/"