# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  name: AWS.EC2.t2micro

steps:
- task: NodeTool@0
- task: NodeTool@0
  inputs:
    versionSource: 'fromFile'
    checkLatest: true
  inputs:
    versionSource: 'spec'
    versionSpec: '10.x'
    checkLatest: true
  displayName: 'Install Node.js'

- script: |
- task: CmdLine@2
  inputs:
    script: |
      echo Write your commands here
      echo Hello world
      pwd
      npm install
      npm run build
  displayName: 'npm install and build'
- task: CmdLine@2
  inputs:
    script: |
      echo Write your commands here
      echo Hello world
      pwd
      npm install
      npm run build